# Generated by Django 3.0.3 on 2020-07-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Postjob_img', models.ImageField(upload_to='static/images')),
                ('Postjob_name', models.CharField(max_length=100)),
                ('Postjob_dis', models.CharField(max_length=300)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
